<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>KCFinder: /<?php echo $this->session['dir'] ?></title>

<link href="/kc/style/type/<?=$this->type ?>" rel="stylesheet" type="text/css" />
<link href="<?=$this->publicPath?>themes/<?=$this->browser['theme']?>/style.css" rel="stylesheet" type="text/css" />
<script src="<?=$this->publicPath?>js/jquery.js" type="text/javascript"></script>
<script src="<?=$this->publicPath?>js/jquery.rightClick.js" type="text/javascript"></script>
<script src="<?=$this->publicPath?>js/jquery.drag.js" type="text/javascript"></script>
<script src="<?=$this->publicPath?>js/helper.js" type="text/javascript"></script>
<script src="<?=$this->publicPath?>getjoiner.js" type="text/javascript"></script>
<script src="<?=$this->publicPath?>gettranslation.php?lang=<?php echo $this->language ?>" type="text/javascript"></script>
<?php if (isset($this->browser['tinyMCE']) ): ?>
<script src="<?= $this->tinyMCEPath ?>/tiny_mce_popup.js" type="text/javascript"></script>
<?php endif; ?>
<?php if (isset($this->init_theme)): ?>
<script src="<?=$this->publicPath?><?=$this->init_theme ?>" type="text/javascript"></script>
<?php endif; ?>
<script type="text/javascript">
browser.version = "<?=$this->browser['version'] ?>";
browser.support.chromeFrame = <?=$this->browser['cromeFrame'] ?>;
browser.support.zip = <?=$this->browser['supportZip'] ?>;
browser.support.check4Update = <?= $this->browser['check4Update'] ?>;
browser.lang = "<?= $this->language ?>";
browser.type = "<?=  $this->browser['type'] ?>";
browser.theme = "<?=  $this->browser['theme'] ?>";
browser.access = <?=  $this->browser['access'] ?>;
browser.dir = "<?=  $this->browser['dir'] ?>";
browser.uploadURL = "<?=  $this->browser['uploadURL'] ?>";
browser.thumbsURL = browser.uploadURL + "/<?=  $this->browser['thumbsDir'] ?>";
<?php if ( $this->setOpener ): ?>
browser.opener.name = "<?= $this->browser['openerName'] ?>";
<?php endif; ?>
<?php if ( $this->browser['isOpenedByCk']|| 1 ): ?>
browser.opener.CKEditor = {};
browser.opener.CKEditor.funcNum = <?php echo '2';/* $this->funcNumCkEditor */ ?>;
<?php endif; ?>
<?php if ($this->browser['tinyMCE'] ): ?>
browser.opener.TinyMCE = true;
<?php endif; ?>
browser.cms = "<?=  $this->browser['cms'] ?>";
_.kuki.domain = "<?=  $this->serverUrl() ?>";
_.kuki.path = "<?=  $this->kuki['path'] ?>";
_.kuki.prefix = "<?=  $this->kuki['prefix'] ?>";
$(document).ready(function() {
    browser.resize();
    browser.init();
    $('#all').css('visibility', 'visible');
});
$(window).resize(browser.resize);
</script>


</head>
<body>
<script type="text/javascript">
$('body').noContext();
</script>
<div id="resizer"></div>
<div id="shadow"></div>
<div id="dialog"></div>
<div id="alert"></div>
<div id="clipboard"></div>

<div id="all">
<div id="left">
    <div id="folders"></div>
</div>
<div id="right">
    <div id="toolbar">
        <div>
        <a href="kcact:upload"><?php echo $this->translator->_("Upload") ?></a>
        <a href="kcact:refresh"><?php echo $this->translator->_("Refresh") ?></a>
        <a href="kcact:settings"><?php echo $this->translator->_("Settings") ?></a>
        <a href="kcact:maximize"><?php echo $this->translator->_("Maximize") ?></a>
        <a href="kcact:about"><?php echo $this->translator->_("About") ?></a>
        <div id="loading"></div>
        </div>
    </div>
    <div id="settings">

    <div>
    <fieldset>
    <legend><?php echo $this->translator->_("View:") ?></legend>
        <table summary="view" id="view"><tr>
        <th><input id="viewThumbs" type="radio" name="view" value="thumbs" /></th>
        <td><label for="viewThumbs">&nbsp;<?php echo $this->translator->_("Thumbnails") ?></label> &nbsp;</td>
        <th><input id="viewList" type="radio" name="view" value="list" /></th>
        <td><label for="viewList">&nbsp;<?php echo $this->translator->_("List") ?></label></td>
        </tr></table>
    </fieldset>
    </div>

    <div>
    <fieldset>
    <legend><?php echo $this->translator->_("Show:") ?></legend>
        <table summary="show" id="show"><tr>
        <th><input id="showName" type="checkbox" name="name" /></th>
        <td><label for="showName">&nbsp;<?php echo $this->translator->_("Name") ?></label> &nbsp;</td>
        <th><input id="showSize" type="checkbox" name="size" /></th>
        <td><label for="showSize">&nbsp;<?php echo $this->translator->_("Size") ?></label> &nbsp;</td>
        <th><input id="showTime" type="checkbox" name="time" /></th>
        <td><label for="showTime">&nbsp;<?php echo $this->translator->_("Date") ?></label></td>
        </tr></table>
    </fieldset>
    </div>

    <div>
    <fieldset>
    <legend><?php echo $this->translator->_("Order by:") ?></legend>
        <table summary="order" id="order"><tr>
        <th><input id="sortName" type="radio" name="sort" value="name" /></th>
        <td><label for="sortName">&nbsp;<?php echo $this->translator->_("Name") ?></label> &nbsp;</td>
        <th><input id="sortType" type="radio" name="sort" value="type" /></th>
        <td><label for="sortType">&nbsp;<?php echo $this->translator->_("Type") ?></label> &nbsp;</td>
        <th><input id="sortSize" type="radio" name="sort" value="size" /></th>
        <td><label for="sortSize">&nbsp;<?php echo $this->translator->_("Size") ?></label> &nbsp;</td>
        <th><input id="sortTime" type="radio" name="sort" value="date" /></th>
        <td><label for="sortTime">&nbsp;<?php echo $this->translator->_("Date") ?></label> &nbsp;</td>
        <th><input id="sortOrder" type="checkbox" name="desc" /></th>
        <td><label for="sortOrder">&nbsp;<?php echo $this->translator->_("Descending") ?></label></td>
        </tr></table>
    </fieldset>
    </div>

    </div>
    <div id="files">
    <div id="content"></div>
    </div>
</div>
<div id="status"><span id="fileinfo">&nbsp;</span></div>
</div>

</body>
</html>
