<?php
if( !isset($this->language ) )
{
	header("Content-Type: text/javascript");
}
else
{
	header("Content-Type: text/javascript; charset={$this->language['_charset']}");
}
if(isset($this->headers))
{
	foreach ($this->headers as $header )
	{
		header($header);
	}

}

if( isset($this->label ) )
{
	// out data
	foreach ($this->label as $english => $native )
	{
		echo "browser.labels['" . $english . "']=\"" . $native . "\";";
	}
}

?>