<?php if(!empty($this->messages)) {
	echo '<p style="padding:10px 10px 10px 10px; margin:5px 0px 5px 0px ;background-color:Khaki;"><b>';
	foreach ($this->messages as $i => $msg) {
		if( $i > 0 )
		   echo '<br />';
		echo $msg;
	}
	echo '</b></p>';
}
?>
<table class="gentable">
	<thead><tr><td width="20px">id</td><td width="200px">miniatura</td><td width="250px">name</td><td width="400px">operazioni</td></tr></thead><tbody>
    <?php $color='odd'?>
	<?php foreach ($this->entries as $entry): ?>
    <?php $id=$this->escape($entry->id) ?>
    <tr class="<?=$color?>"><td><?=$id?></td>
    <td style="text-align: center"><img src = "<?php echo $this->escape($entry->thumbnail);?>" /></td>
    <td><?php echo $this->escape($entry->name) ?></td>
    <td>
    <?php if ($entry->isAllowed('view')): ?>
    <a href="/admin/image/view/id/<?=$id?>"><img src="/images/1300350010_kghostview.png" title="mostra dettagli" /></a>
    <?php endif;?>
    <?php if ($entry->isAllowed('edit')): ?>
    <a href="/admin/image/edit/id/<?=$id?>"><img src="/images/1300350195_edit.png" title="modifica" /></a>
    <?php endif;?>
    <?php if ($entry->isAllowed('delete')): ?>
    <a href="/admin/image/delete/id/<?=$id?>"><img src="/images/delete-24.png" title="elimina immagine" /></a>
    <?php endif;?>
    <?php if ($entry->isAllowed('thumbnail')): ?>
    <a href="/admin/image/thumbnail/id/<?=$id?>"><img src="/images/thumbnail-24.png" title="crea miniatura" /></a>
    <?php endif;?>
    </td>
    
    <!-- $this->url(array('imagename' => 'martel'), 'image') -->
    </tr>
    <?php $color = $color=='odd'?'even':'odd';?>
    <?php endforeach ?>
    </tbody>
    </table>
    <?php echo $this->paginator; ?>
</dl>