<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
 <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
 <?php $this->headLink()->appendStylesheet('/styles/admin.css');?>
 <?php $this->headLink()->appendStylesheet('/styles/adminmenu.css');?>
 <?php echo $this->headTitle(); ?>
 <?php echo $this->headLink(); ?>
 <?php echo $this->headScript(); ?>
 <?php echo $this->inlineScript(); ?>

</head>
<body>
<div id="gallery">
    <img src="/images/it/at1/450px-Grape.JPG" />
    <img src="/images/it/at1/453px-Arnsburger07-3.jpg" />
    <img src="/images/it/at1/800px-Alvani-112.jpg" />
</div>	 
 <script type="text/javascript">
 Galleria.loadTheme('themes/classic/galleria.classic.js');
 $("#gallery").galleria({
     width: 500,
     height: 500,
     debug: true
 });   
 </script>  
</body>
</html> 
