<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type"
	content="application/xhtml+xml; charset=utf-8" />
<?php echo $this->headLink()->appendStylesheet('/styles/global.css') ?>
<?php echo $this->headTitle() ?>
<?php echo $this->headStyle() ?>
<?php echo $this->headScript() ?>
<!-- ciao -->
</head>
<body>
	<div class="external">
		<div class="container_16 clearfix">
			<div class="header">
				<?php echo $this->render('menu.phtml') ?>
			</div>
			<div class=" container_16">
				<div class="content">

					<?php echo $this->layout()->content; ?>
				</div>
				<!-- content -->
			</div>
		</div>
	</div>
</body>
</html>
