<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type"
	content="application/xhtml+xml; charset=utf-8" />
	<?php echo $this->headLink()->appendStylesheet('/styles/global.css') ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headStyle() ?>
	<?php echo $this->headScript() ?>
  <!-- ciao -->
</head>
<body>
	<div class="container_16 clearfix">
	<div class="menu" style="height: 45px; width: 450px;">
	<!-- 
	
	<ul>
	<li><a href="/js/kcfinder/browse.php?type=images&lng=it">Stand Alone</a></li>
	<li><a href="/article/edit/id/1">CK Editor</a></li>
	</ul>
	 -->
	<?php 
	$options = array(
			'ulClass'          => 'left-menu',
			'minDepth'         => 1,
			'maxDepth'         => 1,
			'onlyActiveBranch' => false,
			'renderParents'    => true
	);
	echo $this->navigation()->menu()->renderMenu(null, $options) ?>
	</div>
	
	<div class="main">
	<?php echo $this->layout()->content; ?>
	
	</p>
	</div>
	</div>
</body>
</html>
