

<textarea name="artbuilder[content]" id="artbuilder-content" rows="50" cols="90" style="visibility: hidden; display: none; ">

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non ligula quam. Cras mauris tortor, ultricies ut varius eget, facilisis sed nisl. Praesent pulvinar mattis nulla, quis gravida risus facilisis at. Duis scelerisque consectetur augue, in gravida magna consequat ac. Donec sollicitudin commodo vulputate. Aenean condimentum faucibus gravida. In hac habitasse platea dictumst. Praesent velit nunc, malesuada sit amet vehicula in, condimentum vitae purus. In purus quam, mattis at ornare quis, convallis at ipsum. Suspendisse et viverra enim. Nunc volutpat lorem eget nunc semper rhoncus.
</p>
<p>
Cras sed lorem dolor, a hendrerit leo. Ut eu tellus sit amet sapien rhoncus fringilla non a tortor. Aliquam ac justo a metus malesuada imperdiet. Praesent malesuada sodales ipsum id sagittis. Aliquam leo ipsum, bibendum ut viverra eget, rhoncus sit amet ipsum. Suspendisse sit amet nibh consequat turpis rutrum pellentesque vitae consectetur purus. Donec eleifend eros neque, non molestie purus. Cras et dolor odio.
</p>
<p>
Suspendisse quis metus id odio hendrerit consequat. Nullam gravida, ante id tincidunt ullamcorper, erat nisl semper nisl, ut dignissim velit neque eu eros. Vivamus rutrum dui nec urna consectetur semper. Phasellus laoreet lacinia leo, sed molestie libero tempus quis. Vestibulum lorem libero, molestie sed bibendum sit amet, pretium in enim. Fusce tristique molestie metus id eleifend. Praesent et dui et dolor pulvinar gravida at pulvinar dui. Pellentesque et sapien urna. In nibh odio, mattis id congue vel, sagittis non ante. Curabitur dictum aliquam turpis, at ullamcorper felis fringilla euismod. Nullam tristique, lacus ut consequat semper, elit enim sodales velit, id auctor lectus felis quis sem.
</p>
<p>
Aliquam erat volutpat. Praesent sit amet quam non nulla commodo accumsan a et erat. Sed sit amet tellus arcu, id dictum tellus. Fusce laoreet, augue interdum molestie tempus, lectus libero rhoncus turpis, sit amet aliquam eros ipsum nec dui. Vestibulum adipiscing congue sodales. Nam rutrum mi eget ipsum blandit pellentesque. Cras vel interdum dui. Sed aliquet magna ac lectus bibendum in facilisis sem volutpat. Nullam congue imperdiet est a luctus.
</p>
<p>
Vestibulum mattis, leo quis feugiat tincidunt, lorem nunc tincidunt purus, at feugiat tortor augue quis augue. Phasellus nisi diam, porta et iaculis et, vestibulum id nisi. Phasellus id cursus erat. Aenean orci nibh, vehicula sed fringilla ac, volutpat at augue. Morbi diam urna, fermentum at volutpat sed, aliquam quis nunc. Vestibulum dictum sem metus, sed interdum dui. Pellentesque tempus arcu dui. Nam accumsan nibh quis arcu congue malesuada. Duis a vehicula lorem. Vestibulum hendrerit augue et augue blandit vitae dictum augue fermentum. Duis tristique enim id sapien dapibus viverra. Morbi at massa id lectus posuere mollis. Ut luctus enim quis massa ullamcorper cursus. Quisque lacus quam, dignissim non molestie vel, sodales eu risus. Cras lobortis nulla iaculis nunc tincidunt accumsan.
</p>

</textarea>

<script type="text/javascript">

CKEDITOR.replace( 'artbuilder-content',
	    {
	        toolbar : 'Full',
	        uiColor : '#9AB8F3',
	        resize_enabled: false,
	        height : 400
	        
	    });
</script>
