<div width="900px" height="50px" style="clear:both; margin:10px 10px 10px 10px;"><select>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
</div>
<iframe src="/js/kcfinder/browse.php?type=images&lng=it" width="900px" height="600px" style="background-color:#e0dfde;border-style:solid;border-width:1px;border-color:#c6c6c6;padding:10px 10px 10px 10px;" ></iframe>
