<div height="50px" style="clear:both; margin:20px 10px 20px 10px; float:right;">
<?php echo $this->form; ?>
</div>

<iframe src="/js/kcfinder/browse.php?type=<?=$this->directory?>&lng=<?=$this->language?>&theme=<?=$this->style?>" width="920px" height="600px" style="background-color:<?=$this->ifbackground?>;border-style:solid;border-width:1px;border-color:#c6c6c6;padding:10px 9px 10px 9px;" ></iframe>
